dist: trusty
sudo: false
group: beta
language: node_js
cache:
  directories:
    - $HOME/.npm
node_js:
- 10.3.0
jobs:
  include:
  - stage: test
    script:
    - set -e
    - npm run flow
    - npm run lint
    - npm run test
    - npm run coverage
  - stage: NPM release
    if: tag IS present
    script: echo 'Deploying to NPM...'
    before_deploy: npm run build
    deploy:
      provider: npm
      email: chadima.jiri@gmail.com
      skip_cleanup: true
      api_key: "$NPM_TOKEN"
      on:
        repo: windingtree/wt-js-libs
        tags: true
env:
  global:
  - secure: OeFcbSohWTpMEU5rVBETGz7pYprqgb9rYwgpf39Y59cVM1Ltn4RUx9Tqfl+Chwa8KV7PNI390RSN8sbCE/YxDmUmdaQrx5OYku8KnHgk8ljnCbP3K8A07ehF8B8qe/1n/L+VYOF4lYaXuABut1Cx1kY8LehpOHckeomKGqMaVGqtRiZSz2/AGTMl9jCt7S/6A0T6ddNHMW1wzqzhGdzhz+insUQe6DqoVqpfg46zvs6EglsySUqaecEjDHo3c3REHY6vjqmaOBdkmoCqO45BxCldqTUxzTQjZknoEEJjpygSVAhzpDqUCHrJNXNxJeP7QWl5by6Y/v1ey43XwSY/HrBw/HVIePvrMqbPKj0H/GCybxhqzJuacMu3Zgg2gXgQSVdPsUkp11uQMTRE2/9QFEFlKStsaNTgNGcjW3RvxkAWV+pBU+G4kw8EPl9lppDQADjc6E4R3IvFP7GWiBBBQlLSuC7NCxIASiPQ7mpoB3GEAuCTKBnquhGDCaI9dUyh3MirnSF42oh4y9HgX6QgK3s+aqbr/jEO3F8c+/CSDDvfBhfXNWNzvYCaue1N5ijeWMufJbX9dgsuiTCjdhrkSO6ZkBXfOm74Me0SrIzs9d81uVWRbVcTu369H7b9iOP3+Oxa8nrApjwh8F2x4SiTw+IKF7n/YKnPch0yyk5n3SM=
