dist: trusty
sudo: false
group: beta
language: node_js
cache:
  directories:
  - "$HOME/.npm"
install: case $TRAVIS_BRANCH in greenkeeper*) npm i;; *) npm ci;; esac;
jobs:
  include:
  - stage: test
    script:
    - set -e
    - npm run flow
    - npm run lint
    - npm run test
    - npm run coverage
  - stage: NPM release
    if: tag IS present
    script: echo 'Deploying to NPM...'
    before_deploy: npm run build
    deploy:
      provider: npm
      email: devops@windingtree.com
      skip_cleanup: true
      api_key: "$NPM_TOKEN"
      on:
        repo: windingtree/wt-js-libs
        tags: true
env:
  global:
    secure: a5ewNE5+cD3c479KlkkdR4dG6h8as4TTUOE6kUcZwoaDN4qZZ0t3Q2OBK4g0TOlKD/1oAKUG2Ep7Fw4LeXQqIx6Px79LczfGsZB/yVKWq8wgAvR6MXxyuddq9dcqn5lfvTwSCUFCeTnYhyPwoOriamb/TNrgxr4cwSOPV7h3aMpXOPnEO+CFXkpESqpHmdlC9Bx8womlWGgwseb0AMki1OBlDe3ELges0UH6sVoAODd4bi1jAbrACoj/vDdAa/EJQOH0Znd5w8YLSIcFk8T/E7tuOPGsvLA2yL89LRZwHlkgneHxnr0ss7zZX/smjsuhSnSx7N/9GwY5fcvS4XuVFvSKmXFHOx3lQEmkFMnMPgj+6iTLpDAiQOjXsOC+tM7IiYLOQvMCc+MWgSt/MHqk+qljqxhZlYK0cSOrBFrsVuhNdRCmC552IlVlKAKty5KyH1Ag7qvx0ni/j6UHut+9nlJ4bw4MI6BI/ZndcrZT/mslvTfjT6obDoFaI+FJ/pVORbsvaMyVHBnNv38tyqObuc3+rqAZmJFClX/JMQWceRz4JG0/bLGpES1T9ZBkLCFLxNUXYTh47tdDtQ8JLk4KqYVdD5LL3gAHc/JIgr/YWnTKU+/KijYOqh4RiczKreo/7UIsMjSDh7CV3pojlYxgrKw7+YTyXmgaH+vaZpyO8TY=
